### ISSUE TITLE
Setup button issue

### ISSUE THREAD

**Issue by MrHtgreen** [Thinkersbluff/DGUS-Reloaded_for_CR6-DWIN-SET_Component#40]
For some reason on the latest release when I click setup it just beeps and nothing else. From memory it used to work on the earlier versions

**Comment by Thinkersbluff** [comment]
Sorry for the slow response.  I am dealing with family issues and absent from this project for prolonged periods.

I hope this issue solved itself for you - I was not able to reproduce it on mine.
If your issue was created by a Klipper modification that "broke" t5uid1, you may find that release v1.3.2 resolves the matter.
